name=led_class
version=1.2.8
author=Michel Dufresne
maintainer=Michel Dufresne
sentence=Une librairie pour gérer des LEDs simples et RGB (ESP32 / Arduino).
paragraph=Inclut une classe de base ainsi que deux classes dérivées pour la gestion de LEDs classiques et RGB.
category=Device Control
url=https://github.com/micheldufresne/led_class
architectures=*
includes=ledbase.h, led.h, ledrgb.h
